const MB_ACTION_TYPE = {
  SELECT_FLIGHT: 'mb/SELECT_FLIGHT_SUCCESS',
  SELECT_PAX: 'mb/SELECT_PAX',
  CHECKIN_START: 'mb/CHECKIN_START',
  CHECKIN_SUCCESS: 'mb/CHECKIN_SUCCESS',
  CHECKIN_FAILED: 'mb/CHECKIN_FAILED',
  MB_CLEAR: 'mb/CLEAR'
};
export default MB_ACTION_TYPE;
