export const FLIGHT_ACTION_TYPES = {
  SEARCH_FLIGHT_START: 'flight/SEARCH_FLIGHT_START',
  SEARCH_FLIGHT_SUCCESS: 'flight/SEARCH_FLIGHT_SUCCESS',
  SEARCH_FLIGHT_FAILED: 'flight/SEARCH_FLIGHT_FAILED'
};
