export const FLIGHT_ACTION_TYPES = {
    SEND_SEARCHDTO_START: 'flight/SEND_SEARCHDTO_START',
    SEND_SEARCHDTO_SUCCESS: 'flight/SEND_SEARCHDTO_SUCCESS',
    SEND_SEARCHDTO_FAILED: 'flight/SEND_SEARCHDTO_FAILED',
    FETCH_FLIGHT_START: 'flight/ FETCH_FLIGHT_START',
    FETCH_FLIGHT_SUCCESS: 'flight/ FETCH_FLIGHT_SUCCESS',
    FETCH_FLIGHT_FAILED: 'flight/ FETCH_FLIGHT_FAILED',
};
