export const FLIGHT_ACTION_TYPES = {
  SEARCH_FLIGHT_START: 'flight/SEARCH_FLIGHT_START',
  SEARCH_FLIGHT_SUCCESS: 'flight/SEARCH_FLIGHT_SUCCESS',
  SEARCH_FLIGHT_FAILED: 'flight/SEARCH_FLIGHT_FAILED',

  SELECT_DEPART_ID_START: 'flight/SELECT_DEPART_ID_START',
  SELECT_DEPART_ID_SUCCESS: 'flight/SELECT_DEPART_ID_SUCCESS',

  SELECT_RETURN_ID_START: 'flight/SELECT_RETURN_ID_START',
  SELECT_RETURN_ID_SUCCESS: 'flight/SELECT_RETURN_ID_SUCCESS',

  SELECT_FLIGHT_CLEAR: 'flight/SELECT_FLIGHT_CLEAR'
};
