const BOOKING_ACTION_TYPES = {
  FETCH_BOOKING_BY_PNR_START: 'booking/FETCH_BOOKING_BY_PNR_START',
  FETCH_BOOKING_BY_PNR_SUCCESS: 'booking/FETCH_BOOKING_BY_PNR_SUCCESS',
  FETCH_BOOKING_BY_PNR_FAILED: 'booking/FETCH_BOOKING_BY_PNR_FAILED'
};
export default BOOKING_ACTION_TYPES;
