const BOOKING_ACTION_TYPES = {
  FETCH_BOOKING_BY_PNR_START: 'booking/FETCH_BOOKING_BY_PNR_START',
  FETCH_BOOKING_BY_PNR_SUCCESS: 'booking/FETCH_BOOKING_BY_PNR_SUCCESS',
  FETCH_BOOKING_BY_PNR_FAILED: 'booking/FETCH_BOOKING_BY_PNR_FAILED',

  CREATE_BOOKING_START: 'booking/CREATE_BOOKING_START',
  CREATE_BOOKING_SUCCESS: 'booking/CREATE_BOOKING_SUCCESS',
  CREATE_BOOKING_FAILED: 'booking/CREATE_BOOKING_FAILED',

  BOOKING_CLEAR: 'booking/CLEAR',

  IS_BOOKING_CREATED: 'booking/IS_BOOKING_CREATED'
};

export default BOOKING_ACTION_TYPES;
