const ClaimActiontype = {
  INITIAL_STATE: 'INITIAL_STATE',
  NEXT_STEP: 'NEXT_STEP',
  PREVIOUS_STEP: 'PREVIOUS_STEP',
  ADD_LIFE: 'ADD_LIFE',
  ADD_BENIFIT: 'ADD_BENIFIT',
  ADD_EVENT: 'ADD_EVENT',
  ADD_MEDICAL: 'ADD_MEDICAL',
  ADD_OTHER_INSURANCE: 'ADD_OTHER_INSURANCE',
  ADD_PAYMENT_METHOD: 'ADD_PAYMENT_METHOD',
  ADD_IMAGES: 'ADD_IMAGES',
  APPLY_FORM_START: 'APPLY_FORM_START',
  APPLY_FORM_SUCCESS: 'APPLY_FORM_SUCCESS',
  APPLY_FORM_FAILED: 'APPLY_FORM_FAILED',
  APPLY_FORM_PROCESSING: 'APPLY_FORM_PROCESSING',
  DOWNLOAD_PDF_FILE: 'DOWNLOAD_PDF_FILE',
  SET_ACTIVE_STEP: 'SET_ACTIVE_STEP',
  SET_APPLYFORM_VALID: 'SET_APPLYFORM_VALID'
};
export default ClaimActiontype;
