export const PASSENGER_ACTION_TYPES = {
  CREATE_PASSENGER_START: 'passenger/CREATE_PASSENGER_START',
  CREATE_PASSENGER_SUCCESS: 'passenger/CREATE_PASSENGER_SUCCESS',
  CREATE_PASSENGER_FAILED: 'passenger/CREATE_PASSENGER_FAILED',

  HAVE_PASSENGER_SUCCESS: 'passenger/HAVE_PASSENGER_SUCCESS'
};
