export const PASSENGER_ACTION_TYPES = {
  CREATE_PASSENGER_START: 'passenger/CREATE_PASSENGER_START',
  CREATE_PASSENGER_SUCCESS: 'passenger/CREATE_PASSENGER_SUCCESS',
  CREATE_PASSENGER_FAILED: 'passenger/CREATE_PASSENGER_FAILED',

  CREATE_BOOKINGS_START: 'passenger/CREATE_BOOKINGS_START',
  CREATE_BOOKINGS_SUCCESS: 'passenger/CREATE_BOOKINGS_SUCCESS',
  CREATE_BOOKINGS_FAILED: 'passenger/CREATE_BOOKINGS_FAILED',

  CLEAR_PASSENGERS: 'passenger/CLEAR_PASSENGERS'
};
