export const MEMBER_ACTION_TYPES = {
    SET_CURRENT_MEMBER: "member/SET_CURRENT_MEMBER",
    CHECK_MEMBER_SESSION: "member/CHECK_MEMBER_SESSION",
    GOOGLE_SIGN_IN_START: "member/GOOGLE_SIGN_IN_START",
    EMAIL_SIGN_IN_START: "member/EMAIL_SIGN_IN_START",
    SIGN_IN_SUCCESS: "member/SIGN_IN_SUCCESS",
    SIGN_IN_FAILED: "member/SIGN_IN_FAILED",
    SIGN_UP_START: "member/SIGN_UP_START",
    SIGN_UP_SUCCESS: "member/SIGN_UP_SUCCESS",
    SIGN_UP_FAILED: "member/SIGN_UP_FAILED",
    SIGN_OUT_START: "member/SIGN_OUT_START",
    SIGN_OUT_SUCCESS: "member/SIGN_OUT_SUCCESS",
    SIGN_OUT_FAILED: "member/SIGN_OUT_FAILED",
};
