export const SEAT_ACTION_TYPES = {
  FETCH_SEATS_START: 'seat/FETCH_SEATS_START',
  FETCH_SEATS_SUCCESS: 'seat/FETCH_SEATS_SUCCESS',
  FETCH_SEATS_FAILED: 'seat/FETCH_SEATS_FAILED',
  UPDATE_SEATS: 'seat/UPDATE_SEATS',
  CLEAR_SEATS: 'seat/CLEAR_SEATS'
};
