export const ITINERARY_ACTION_TYPES = {
//   FETCH_BOOKINGS_START: 'itinerary/FETCH_BOOKINGS_START',
//   FETCH_BOOKINGS_SUCCESS: 'itinerary/FETCH_BOOKINGS_SUCCESS',
//   FETCH_BOOKINGS_FAILED: 'itinerary/FETCH_BOOKINGS_FAILED',

  FETCH_COMPLETED_PAYPAL_START: 'itinerary/FETCH_COMPLETED_PAYPAL_START',
  FETCH_COMPLETED_PAYPAL_SUCCESS: 'itinerary/FETCH_COMPLETED_PAYPAL_SUCCESS',
  FETCH_COMPLETED_PAYPAL_FAILED: 'itinerary/FETCH_COMPLETED_PAYPAL_FAILED'
};
