export const ITINERARY_ACTION_TYPES = {

  FETCH_COMPLETED_PAYPAL_START: 'itinerary/FETCH_COMPLETED_PAYPAL_START',
  FETCH_COMPLETED_PAYPAL_SUCCESS: 'itinerary/FETCH_COMPLETED_PAYPAL_SUCCESS',
  FETCH_COMPLETED_PAYPAL_FAILED: 'itinerary/FETCH_COMPLETED_PAYPAL_FAILED',

  SEND_EMAIL_START: 'itinerary/SEND_EMAIL_START',
  SEND_EMAIL_SUCCESS: 'itinerary/SEND_EMAIL_SUCCESS',
  SEND_EMAIL_FAILED: 'itinerary/SEND_EMAIL_FAILED'
};
