const AIRPORT_ACTION_TYPES = {
  FETCH_AIRPORT_START: 'airport/FETCH_AIRPORT_START',
  FETCH_AIRPORT_SUCCESS: 'airport/FETCH_AIRPORT_SUCCESS',
  FETCH_AIRPORT_FAILED: 'airport/FETCH_AIRPORT_FAILED'
}
export default AIRPORT_ACTION_TYPES;